load_lib zig-support.exp
require {can_compile zig}
standard_testfile .zig

if { [prepare_for_testing "failed to prepare" \
	${testfile} ${srcfile} "zig"] } {
    return
}

if {![runto ${srcfile}:3]} {
    untested "could not run to breakpoint"
    return -1
}

gdb_test "print a" {= 3 '\\003'} "print a before adding 1"

if {![runto ${srcfile}:5]} {
    untested "could not run to breakpoint"
    return -1
}

gdb_test "print a" {= 4 '\\004'} "print a after adding 1"
